---

- name: Install Hive
  become: yes
  yum:
    name:
      - hive
      - hive-metastore
      - hive-server2
  tags:
    - hive

- name: Configure hive-site.xml
  become: yes
  copy:
    src: hive-site.xml
    dest: /etc/hive/conf
  tags:
    - hive

- name: Create symbolic link to MySQL JDBC
  become: yes
  file:
    src: /usr/share/java/mysql-connector-java.jar
    dest: /usr/lib/hive/lib/mysql-connector-java.jar
    state: link
  tags:
    - hive

- name: Create database
  shell: |
    mysql -u root -e "CREATE DATABASE metastore;"
    mysql -u root -e "CREATE USER hive@localhost IDENTIFIED BY 'hive';"
    mysql -u root -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM hive@localhost;"
    mysql -u root -e "GRANT ALL PRIVILEGES ON metastore.* TO hive@localhost;"
    mysql -u root -e "FLUSH PRIVILEGES;"
  tags:
    - hive
    - hive:init

- name: Initialize schema
  shell: /usr/lib/hive/bin/schematool -dbType mysql -initSchema
  environment:
    JAVA_HOME: /usr/lib/jvm/jre
  tags:
    - hive
    - hive:init

- name: Start Metastore
  become: yes
  shell: service hive-metastore start
  tags:
    - hive

- name: Start HiveServer2
  become: yes
  shell: service hive-server2 start
  tags:
    - hive
