---

- name: Install Hive
  become: yes
  yum:
    name:
      - hive
      - hive-metastore
      - hive-server2
  tags:
    - hive

- name: Install pip
  become: yes
  yum:
    name: python-pip
  tags:
    - hive

- name: Install psycopg2
  become: yes
  pip:
    name: psycopg2==2.7.5
  tags:
    - hive

- name: Create user
  become: yes
  become_user: postgres
  postgresql_user:
    name: hive
    login_password: hive
    state: present
  tags:
    - hive

- name: Create metastore
  become: yes
  become_user: postgres
  postgresql_db:
    name: metastore
    owner: hive
    encoding: UTF8
  tags:
    - hive

- name: Configure database
  become: yes
  become_user: postgres
  postgresql_set:
    name: standard_conforming_strings
    value: "off"
  tags:
    - hive
