---

- name: Install MariaDB
  become: yes
  yum:
    name:
      - mariadb-server
      - mysql-connector-java
  tags:
    - mariadb

- name: Start MariaDB
  become: yes
  systemd:
    name: mariadb
    state: restarted
    enabled: yes
  tags:
    - mariadb
